name = "bot_server"
account_id = ""
workers_dev = true
compatibility_date = "2022-02-19"
main = "./build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

